name: "Formatting"
description: "Lint + Prettier + CSpell"
inputs:
  dir:
    description: formatting folder
    required: true
runs:
  using: "composite"
  steps:
    - name: Lint
      run: npm run lint ${{ inputs.dir }}
      shell: bash
