name: Block merge to develop

on:
  pull_request:
    types: [labeled, unlabeled]
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    if: ${{github.event.label.name == 'block merge'}}
    runs-on: ubuntu-latest
    steps:
      - uses: dayone-jp/target-branch-labeler@main
        if: ${{github.event.action == 'labeled'}}
        with:
          type: "add"
          release-source-branch: shared-change
          label: "block"
      - uses: dayone-jp/target-branch-labeler@main
        if: ${{github.event.action == 'unlabeled'}}
        with:
          type: "remove"
          release-source-branch: shared-change
          label: "block"
