name: Block merge rule

on:
  pull_request:
    types: [labeled, unlabeled]
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: write-all

jobs:
  e2e:
    if: ${{github.event.label.name == 'block merge'}}
    runs-on: ubuntu-latest
    steps:
      - name: Lock
        if: ${{github.event.action == 'labeled'}}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TEST_KEY}}
          script: |
            github.request('PUT /repos/{owner}/{repo}/rulesets/{ruleset_id}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'shared-change',
              ruleset_id: 43641,
              enforcement: 'active',
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            })

      - name: Unlock
        if: ${{github.event.action == 'unlabeled'}}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TEST_KEY}}
          script: |
            github.request('PUT /repos/{owner}/{repo}/rulesets/{ruleset_id}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'shared-change',
              ruleset_id: 43641,
              enforcement: 'disabled',
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            })
