name: Folder 2

env:
  app_name: folder2

on:
  pull_request_review:
    types: [submitted]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{toJson(github.event.pull_request)}}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install Deps
        working-directory: folder1
        run: bun install
      - name: Run Env
        working-directory: folder1
        run: bun dev &
      - name: Run tests
        working-directory: e2e
        run: |
          npm install
