name: Folder 2

env:
  app_name: folder2

on:
  pull_request:
    types: labeled
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: dayone-jp/target-branch-labeler@main
        with:
          release-target-branch: main
          release-source-branch: shared-change
          label: "kek"
