name: Folder 2

env:
  app_name: folder2

on:
  check_run:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: |
          echo ${{ github.event.check_run.name }}}
