name: Folder 2

env:
  app_name: folder2

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [develop, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  split-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - working-directory: "e2e"
        run: "bash split_test_files.sh 3"
      - uses: actions/upload-artifact@v3
        with:
          name: specs
          path: tmp
  e2e:
    strategy:
      fail-fast: false
      matrix:
        spec: ["1", "2", "3"]
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    needs: split-tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/download-artifact@v3
        with:
          name: specs
      - run: ls
      - name: Run Env
        working-directory: folder1
        run: bun dev &
      - name: Run tests
        working-directory: e2e
        run: |
          npm install
          files=$(paste -sd "," "../spec_0${{matrix.spec}}")
          npm run cypress:run:specs $files
      - name: Save screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          if-no-files-found: ignore
          path: e2e/cypress/screenshots/**
