name: Folder 2

env:
  app_name: folder2

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "./folder2/**"
      - "./shared/**"
  push:
    paths:
      - "./folder1/**"
      - "./shared/**"
    # branches: [develop, master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - uses: "./.github/actions/format"
        with:
          dir: ${{env.app_name}}
