name: Shared CI

env:
  app_name: shared

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "./shared/**"
  push:
    paths:
      - "./folder1/**"
      - "./shared/**"
    # branches: [develop, master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/actions/format"
        with:
          dir: ${{env.app_name}}
