name: E2E for feature branch

on:
  # in this case we want to run workflow when we push `Update branch` button in GitHub
  # if you do this, it removes all successfull checks, but not the approvals so e2e stuck :(
  pull_request:
    types: [synchronize, labeled]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref }}-feature
  cancel-in-progress: true

jobs:
  should-run:
    # second argument for `synchronize` event support
    if: ${{(github.event.label.name == 'approved' || contains(github.event.pull_request.labels.*.name, 'approved')) && github.event.pull_request.state != 'closed'}}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.event.pull_request.state}}
      - run: echo "Unsuccessful"
